In [1]:
import numpy as np

In [2]:
list1 = [1,2,3,4]

In [3]:
n1 = np.array(list1)

In [4]:
n1

array([1, 2, 3, 4])

In [5]:
type(n1)

numpy.ndarray

In [6]:
n2 = np.array([[1,2,3,4],[5,6,7,8]])

In [7]:
n2

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [8]:
n2.shape

(2, 4)

In [9]:
n1.shape

(4,)

In [10]:
n2

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [12]:
n2.shape = (4,2)

In [13]:
n2

array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 8]])

In [14]:
n2.shape = (1,8)

In [15]:
n2

array([[1, 2, 3, 4, 5, 6, 7, 8]])

In [16]:
n3 = np.zeros((1,2))

In [17]:
n3

array([[0., 0.]])

In [21]:
n4 = np.zeros((15,15))

In [22]:
n4

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.

In [23]:
n5 = np.full((2,4),10)

In [24]:
n5

array([[10, 10, 10, 10],
       [10, 10, 10, 10]])

In [30]:
n6 = np.arange(11,21)

In [31]:
n6

array([11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

In [34]:
n7 = np.arange(0,100,5)

In [35]:
n7

array([ 0,  5, 10, 15, 20, 25, 30, 35, 40, 45, 50, 55, 60, 65, 70, 75, 80,
       85, 90, 95])

In [42]:
n8 = np.random.randint(1,100,5)

In [43]:
n8

array([76, 57,  1, 60,  7])

In [44]:
n1 = np.array([10,20,30])

In [45]:
n2 = np.array([11,21,31])

In [46]:
n3 = np.vstack((n1,n2))

In [47]:
n3

array([[10, 20, 30],
       [11, 21, 31]])

In [48]:
n4 = np.hstack((n1,n2))

In [49]:
n4

array([10, 20, 30, 11, 21, 31])

In [50]:
n5 = np.column_stack((n1,n2))

In [51]:
n5

array([[10, 11],
       [20, 21],
       [30, 31]])

In [52]:
n1 = np.array([10,20,30,40,50,60])

In [53]:
n2 = np.array([40,50,60,70,80,90])

In [54]:
n3 = np.intersect1d(n1,n2)

In [55]:
n3

array([40, 50, 60])

In [56]:
n4 = np.setdiff1d(n1,n2)

In [57]:
n4

array([10, 20, 30])

In [58]:
n5 = np.setdiff1d(n2,n1)

In [59]:
n5

array([70, 80, 90])

In [60]:
n6 = np.sum([n1,n2])

In [61]:
n6

600

In [64]:
n7 = np.sum([n1,n2],axis=1)

In [65]:
n7

array([210, 390])

In [95]:
n1 = np.array([1,2,3])

In [87]:
n8 = n1 / 5

In [88]:
n8

array([ 2.,  4.,  6., 10., 12., 16.,  8.])

In [89]:
meanNum = np.mean(n1)

In [90]:
meanNum

41.42857142857143

In [91]:
medNum = np.median(n1)

In [92]:
medNum

40.0

In [96]:
stdNum = np.std(n1)

In [97]:
stdNum

0.816496580927726

In [98]:
np.save("my_array",n1)

In [99]:
nLoad = np.load("my_array.npy")

In [100]:
nLoad

array([1, 2, 3])